name: CI/CD staging Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.53.235.114 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/Deploying-on-AWS
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart fe-sever || pm2 start npm --name "fe-sever" --cwd /home/ubuntu/Deploying-on-AWS/apps/web -- run start
            pm2 restart http-sever || pm2 start dist/index.js --name "http-sever" --cwd /home/ubuntu/Deploying-on-AWS/apps/http-server
            pm2 restart ws-sever || pm2 start dist/index.js --name "ws-sever" --cwd /home/ubuntu/Deploying-on-AWS/apps/websocket-server
          EOF
